name: linky
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native: ^0.1.0
  metadata_fetch: ^0.4.2
  url_launcher: ^6.2.4
  share_plus: ^7.2.1
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0

  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  http: ^1.4.0 # ✅ 요약 요청용 HTTP 추가

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/Linky.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/Linky.png

flutter_native_splash:
  color: '#FEFEE9'
  image: assets/images/Linky.png
  android: true
  ios: true
